# Generated by Django 2.2.10 on 2021-01-14 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=500, unique=True, verbose_name='E-mail')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('phone', models.CharField(blank=True, max_length=40, null=True, verbose_name='Телефон')),
                ('phone_confirmed', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('gender', models.CharField(blank=True, choices=[('male', 'М'), ('female', 'Ж')], max_length=40, null=True, verbose_name='Пол')),
                ('city', models.CharField(blank=True, max_length=500)),
                ('password', models.CharField(blank=True, max_length=500)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('was_active', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=False)),
                ('corporate', models.BooleanField(default=False)),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='День рождения')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Languages', verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=500, verbose_name='Город')),
                ('street', models.CharField(max_length=500, verbose_name='Улица')),
                ('house', models.CharField(max_length=500, verbose_name='Дом')),
                ('appartment', models.CharField(max_length=500, verbose_name='Квартира / Офис')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserNP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=500)),
                ('branch', models.CharField(max_length=500)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='np', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscripton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ManyToManyField(related_name='subscription', to='catalogue.Category')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка на категории',
                'verbose_name_plural': 'Подписка на категории',
            },
        ),
        migrations.CreateModel(
            name='UserNPChosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserNP')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='np_chosen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=500, verbose_name='ЕДРПОУ')),
                ('email', models.EmailField(max_length=500, unique=True, verbose_name='Корпоративный E-mail')),
                ('iban', models.CharField(blank=True, max_length=500, verbose_name='Номер счета (IBAN)')),
                ('director', models.CharField(blank=True, max_length=500, verbose_name='ФИО Директора')),
                ('adress', models.CharField(blank=True, max_length=500, verbose_name='Юридический адрес')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdressChosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserAdress')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adress_chosen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product', verbose_name='Товар')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
