# Generated by Django 2.2.10 on 2021-01-14 05:22

import apps.core.functions.function__filefield
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('en', 'ENG'), ('ru', 'РУС'), ('uk', 'УКР')], max_length=10, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Активный язык',
                'verbose_name_plural': 'Активные языки',
            },
        ),
        migrations.CreateModel(
            name='MainData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_childs', models.BooleanField(default=False, verbose_name='Перевод')),
                ('logo', apps.core.functions.function__filefield.FileField(blank=True, null=True, upload_to='file_codes', verbose_name='Логотип сайта')),
                ('favicon', apps.core.functions.function__filefield.FileField(blank=True, null=True, upload_to='file_codes', verbose_name='Fav icon')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('adress', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('meta_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Мета тег Titile (Домашней страницы)')),
                ('meta_descr', models.TextField(blank=True, max_length=500, null=True, verbose_name='Мета тег Description (Домашней страницы)')),
                ('seo_text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='SEO текст (Домашней страницы)')),
            ],
            options={
                'verbose_name': 'Основная информация',
                'verbose_name_plural': 'Основная информация',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Время отправки')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=255, verbose_name='Телефон')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст письма')),
            ],
            options={
                'verbose_name': 'Сообщения',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='MainDataTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate', models.BooleanField(default=True, verbose_name='Перевести')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='E-mail')),
                ('adress', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('meta_title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Мета тег Titile (Домашней страницы)')),
                ('meta_descr', models.TextField(blank=True, max_length=500, null=True, verbose_name='Мета тег Description (Домашней страницы)')),
                ('seo_text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='SEO текст (Домашней страницы)')),
                ('translation', models.BooleanField(default=False, verbose_name='Перевести')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Languages', verbose_name='Язык')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='core.MainData')),
            ],
            options={
                'verbose_name': 'Основная информация (перевод)',
                'verbose_name_plural': 'Основная информация (перевод)',
            },
        ),
    ]
