# Generated by Django 2.2.10 on 2021-01-14 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_old', models.CharField(blank=True, choices=[('new', 'Новый заказ'), ('created', 'Создан, ожидает оплаты'), ('payed', 'Оплачен, в обработке'), ('prepered', 'Собран, ожидает передачи на доставку'), ('at_delivry', 'Передан на доставку'), ('delivring', 'Доставляется'), ('delivred', 'Доставлен'), ('declined', 'Отменен')], editable=False, max_length=255, null=True, verbose_name='Статус заказа')),
                ('status', models.CharField(choices=[('new', 'Новый заказ'), ('created', 'Создан, ожидает оплаты'), ('payed', 'Оплачен, в обработке'), ('prepered', 'Собран, ожидает передачи на доставку'), ('at_delivry', 'Передан на доставку'), ('delivring', 'Доставляется'), ('delivred', 'Доставлен'), ('declined', 'Отменен')], max_length=255, verbose_name='Статус заказа')),
                ('pay_type', models.CharField(choices=[('np', 'Наложеный платежь'), ('card', 'Оплата картой на сайте'), ('cash', 'Наличными при получении')], max_length=255, verbose_name='Способ оплаты')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Время заказа')),
                ('payed', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Время оплаты')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Розничная')),
                ('price_ua', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Розничная, грн.')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Всего')),
                ('total_ua', models.DecimalField(decimal_places=2, default=0, max_digits=200, verbose_name='Всего, грн.')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='order.Order', verbose_name='Продукт')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товар в заказе',
            },
        ),
        migrations.CreateModel(
            name='OrderDeliveryNP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Город')),
                ('branch', models.CharField(blank=True, max_length=50, verbose_name='Номер отделения')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'verbose_name': 'Доставка Новой почтой',
                'verbose_name_plural': 'Доставка Новой почтой',
            },
        ),
        migrations.CreateModel(
            name='OrderDeliveryCurier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Город')),
                ('street', models.CharField(blank=True, max_length=50, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=50, verbose_name='Дом')),
                ('appartment', models.CharField(blank=True, max_length=50, verbose_name='Квартира')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
            options={
                'verbose_name': 'Доставка курьером',
                'verbose_name_plural': 'Доставка курьером',
            },
        ),
    ]
