# Generated by Django 2.2.10 on 2021-01-14 05:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.PositiveIntegerField(default=0, verbose_name='№')),
                ('image', models.FileField(blank=True, max_length=1024, null=True, upload_to='', verbose_name='Изображение')),
                ('image_thmb', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('translate_childs', models.BooleanField(default=False, verbose_name='Перевод')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Заголовок')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка')),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннера',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Сообщения',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='PopularCategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(blank=True, max_length=1024, null=True, upload_to='', verbose_name='Изображение')),
                ('image_thmb', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('num', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Популярная категория',
                'verbose_name_plural': 'Популярные категории',
            },
        ),
        migrations.CreateModel(
            name='BannerTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate', models.BooleanField(default=True, verbose_name='Перевести')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Заголовок')),
                ('link', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ссылка')),
                ('translation', models.BooleanField(default=False, verbose_name='Перевести')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Languages', verbose_name='Язык')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='shop.Banner')),
            ],
            options={
                'verbose_name': 'Баннер (перевод)',
                'verbose_name_plural': 'Баннера (перевод)',
            },
        ),
    ]
