# Generated by Django 2.2.10 on 2021-01-14 05:22

import ckeditor.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num', models.PositiveIntegerField(default=0, verbose_name='№')),
                ('image', models.FileField(blank=True, max_length=1024, null=True, upload_to='', verbose_name='Изображение')),
                ('image_thmb', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('translate_childs', models.BooleanField(default=False, verbose_name='Перевод')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Статичная страница',
                'verbose_name_plural': 'Статичные страницы',
            },
        ),
        migrations.CreateModel(
            name='PageAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_childs', models.BooleanField(default=False, verbose_name='Перевод')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Страница: О нас',
                'verbose_name_plural': 'Страница: О нас',
            },
        ),
        migrations.CreateModel(
            name='PageContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_childs', models.BooleanField(default=False, verbose_name='Перевод')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст')),
                ('phone', models.CharField(blank=True, max_length=500, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=500, null=True, verbose_name='Адрес электронной почты')),
            ],
            options={
                'verbose_name': 'Страница: Котнакты',
                'verbose_name_plural': 'Страница: Котнакты',
            },
        ),
        migrations.CreateModel(
            name='PageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate_childs', models.BooleanField(default=False, verbose_name='Перевод')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
            ],
            options={
                'verbose_name': 'Статичная страница | Группа',
                'verbose_name_plural': 'Статичные страницы | Группы',
            },
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate', models.BooleanField(default=True, verbose_name='Перевести')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
                ('text', ckeditor.fields.RichTextField(verbose_name='Текст')),
                ('translation', models.BooleanField(default=False, verbose_name='Перевести')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Languages', verbose_name='Язык')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='pages.Page')),
            ],
            options={
                'verbose_name': 'Статичная страница (перевод)',
                'verbose_name_plural': 'Статичные страницы (перевод)',
            },
        ),
        migrations.CreateModel(
            name='PageGroupTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate', models.BooleanField(default=True, verbose_name='Перевести')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, max_length=250, null=True, verbose_name='Иденитификатор')),
                ('translation', models.BooleanField(default=False, verbose_name='Перевести')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Languages', verbose_name='Язык')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='pages.PageGroup')),
            ],
            options={
                'verbose_name': 'Статичная страница | Группа (перевод)',
                'verbose_name_plural': 'Статичные страницы | Группы (перевод)',
            },
        ),
        migrations.CreateModel(
            name='PageContactsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate', models.BooleanField(default=True, verbose_name='Перевести')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст')),
                ('phone', models.CharField(blank=True, max_length=500, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=500, null=True, verbose_name='Адрес электронной почты')),
                ('translation', models.BooleanField(default=False, verbose_name='Перевести')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Languages', verbose_name='Язык')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='pages.PageContacts')),
            ],
            options={
                'verbose_name': 'Страница: Котнакты (перевод)',
                'verbose_name_plural': 'Страница: Котнакты (перевод)',
            },
        ),
        migrations.CreateModel(
            name='PageAboutTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translate', models.BooleanField(default=True, verbose_name='Перевести')),
                ('text', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст')),
                ('translation', models.BooleanField(default=False, verbose_name='Перевести')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Languages', verbose_name='Язык')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='pages.PageAbout')),
            ],
            options={
                'verbose_name': 'Страница: О нас (перевод)',
                'verbose_name_plural': 'Страница: О нас (перевод)',
            },
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='pages.PageGroup', verbose_name='Группа'),
        ),
    ]
